FROM oven/bun:1 AS base
WORKDIR /app

FROM base AS install
COPY package.json bun.lock ./
COPY apps/api/package.json ./apps/api/package.json
COPY apps/web/package.json ./apps/web/package.json

RUN bun install --frozen-lockfile

FROM base AS release
COPY --from=install /app/node_modules ./node_modules
COPY --from=install /app/bun.lock ./bun.lock
COPY --from=install /app/package.json ./package.json

COPY apps/web ./apps/web

WORKDIR /app/apps/web
ENV NODE_ENV=development

EXPOSE 3000
CMD ["bun", "dev"]
